
service: serverless-rust-aws
frameworkVersion: '3'
configValidationMode: error
provider:
  name: aws
  memorySize: 128
  region: us-east-1
plugins:
  # this registers the plugin with serverless
  - ../src/index.js
  # - serverless-rust-aws - uncomment this when installing from npm
package:
  individually: true

functions:
  hello_world:
    # paths to your rust binary {projectDir}.{projectBinary}
    handler: hello_world.hello_world
    runtime: provided.al2 # needed to run on aws
    tags:
      rust: true # our script needs to know what functions to package
